### ISSUE TITLE
re: an error message

### ISSUE THREAD

**Issue by AmosG8** [GKalliatakis/Video-Recording-using-Matlab-GUIDE-#1]
Hi,
thanks for sharing! I've just run it and am getting the following error message. Could you resolve? 

Error using videoinput (line 219)
Invalid ADAPTORNAME specified. Type 'imaqhwinfo' for a list of available ADAPTORNAMEs. Image acquisition adaptors may be
available as downloadable support packages. Open Add-Ons Explorer to install additional adaptors.

Error in untitled>vdrecord_Callback (line 164)
vid = videoinput('macvideo', 1, 'YCbCr422_1280x720');

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in untitled (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)untitled('vdrecord_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

Note, I've installed an adapter so that: 

imaqhwinfo

ans = 

  struct with fields:

    InstalledAdaptors: {'winvideo'}
        MATLABVersion: '9.3 (R2017b)'
          ToolboxName: 'Image Acquisition Toolbox'
       ToolboxVersion: '5.3 (R2017b)'

**Comment by GKalliatakis** [comment]
Hi, this code has been tested on a Mac machine, therefore the following line

`vid = videoinput('macvideo', 1, 'YCbCr422_1280x720');
`

must be changed to your installed adaptor accordingly.

**Comment by AmosG8** [comment]
Great! Thanks a lot for the prompt answer. I've changed to
vid = videoinput('winvideo', 1, 'MJPG_1280x720')
and it works.

Now, is it possible to integrate this within a larger GUI I have?

**Comment by GKalliatakis** [comment]
I've never tested under a larger GUI but I cannot see a reason why it won't work.

**Comment by AmosG8** [comment]
yup, the question is how to integrate - how I call your code from a larger
code, and graphically, any idea how I integrate your GUI using GUIDE into
my GUI?
